/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        surface: '#fff8f7',
        'surface-dim': '#f2d3d1',
        'surface-bright': '#fff8f7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fff0ef',
        'surface-container': '#ffe9e8',
        'surface-container-high': '#ffe1e0',
        'surface-container-highest': '#fbdbda',
        'on-surface': '#281717',
        'on-surface-variant': '#5c403f',
        'inverse-surface': '#3f2c2b',
        'inverse-on-surface': '#ffedeb',
        outline: '#906f6e',
        'outline-variant': '#e5bdbb',
        'surface-tint': '#bf0229',
        primary: '#9e001f',
        'on-primary': '#ffffff',
        'primary-container': '#c8102e',
        'on-primary-container': '#ffdad8',
        'inverse-primary': '#ffb3b1',
        secondary: '#805600',
        'on-secondary': '#ffffff',
        'secondary-container': '#fdaf11',
        'on-secondary-container': '#694600',
        tertiary: '#005a15',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#00751f',
        'on-tertiary-container': '#93f990',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdad8',
        'primary-fixed-dim': '#ffb3b1',
        'on-primary-fixed': '#410007',
        'on-primary-fixed-variant': '#92001c',
        'secondary-fixed': '#ffddb0',
        'secondary-fixed-dim': '#ffba45',
        'on-secondary-fixed': '#281800',
        'on-secondary-fixed-variant': '#614000',
        'tertiary-fixed': '#94f990',
        'tertiary-fixed-dim': '#78dc77',
        'on-tertiary-fixed': '#002204',
        'on-tertiary-fixed-variant': '#005313',
        background: '#fff8f7',
        'on-background': '#281717',
        'surface-variant': '#fbdbda',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        'container-max': '1280px',
      },
      fontFamily: {
        'hero-title': ['Fira Sans', 'sans-serif'],
        'hero-title-mobile': ['Fira Sans', 'sans-serif'],
        'section-title': ['Fira Sans', 'sans-serif'],
        'card-title': ['Fira Sans', 'sans-serif'],
        body: ['Fira Sans', 'sans-serif'],
        caption: ['Fira Sans', 'sans-serif'],
      },
      fontSize: {
        'hero-title': ['56px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'hero-title-mobile': ['36px', { lineHeight: '1.2', fontWeight: '700' }],
        'section-title': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'card-title': ['18px', { lineHeight: '1.4', fontWeight: '500' }],
        body: ['15px', { lineHeight: '1.6', fontWeight: '400' }],
        caption: ['12px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '300' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
      boxShadow: {
        ambient: '0 4px 20px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
